services:
  - name: ema-backend
    type: web
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://emaUser:<db_password>@cluster0.oqd80zs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: DB_NAME
        value: test_database
      - key: SECRET_KEY
        value: ema-nextgen-intrusion-detection-system-secret-key
    healthCheckPath: /

 - name: ema-frontend
    type: web
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://newema.onrender.com
